In [ ]:
import pandas as pd
data={
    'Department':['HR','Sales','IT','Sales','IT','HR','Sales'],
    'Employee':['A','B','C','D','E','F','G'],
    'Salary':[50000,60000,45000,48000,70000,72000,71000],
    'Experience':[2,4,3,5,6,7,5]
}
df=pd.DataFrame(data)
print(df)

  Department Employee  Salary  Experience
0         HR        A   50000           2
1      Sales        B   60000           4
2         IT        C   45000           3
3      Sales        D   48000           5
4         IT        E   70000           6
5         HR        F   72000           7
6      Sales        G   71000           5

In [ ]:
df.groupby(['Department','Experience']).sum()
print(df)

  Department Employee  Salary  Experience
0         HR        A   50000           2
1      Sales        B   60000           4
2         IT        C   45000           3
3      Sales        D   48000           5
4         IT        E   70000           6
5         HR        F   72000           7
6      Sales        G   71000           5

In [ ]:
df3=df.groupby('Experience').sum()
print(df3)

            Department Employee  Salary
Experience
2                   HR        A   50000
3                   IT        C   45000
4                Sales        B   60000
5           SalesSales       DG  119000
6                   IT        E   70000
7                   HR        F   72000

In [ ]:
df.groupby('Department')['Salary'].sum()

Department
HR       122000
IT       115000
Sales    179000
Name: Salary, dtype: int64

In [ ]:
df1=df.groupby(['Department','Experience']).sum()
print(df1)

                      Employee  Salary
Department Experience
HR         2                 A   50000
           7                 F   72000
IT         3                 C   45000
           6                 E   70000
Sales      4                 B   60000
           5                DG  119000

In [ ]:
df2=df.groupby('Department').sum()
print(df2)

           Employee  Salary  Experience
Department
HR               AF  122000           9
IT               CE  115000           9
Sales           BDG  179000          14

In [ ]:
df5=df.groupby('Department')['Salary'].mean()
print(df5)

Department
HR       61000.000000
IT       57500.000000
Sales    59666.666667
Name: Salary, dtype: float64

In [ ]:
df.groupby('Department').agg({
    'Salary':'sum','Experience':'mean'
})
print(df)

  Department Employee  Salary  Experience
0         HR        A   50000           2
1      Sales        B   60000           4
2         IT        C   45000           3
3      Sales        D   48000           5
4         IT        E   70000           6
5         HR        F   72000           7
6      Sales        G   71000           5

In [ ]:
df9=df['Dept_Avg_Salary']=df.groupby('Department')['Salary'].transform('mean')
print(df9)

0    61000.000000
1    59666.666667
2    57500.000000
3    59666.666667
4    57500.000000
5    61000.000000
6    59666.666667
Name: Salary, dtype: float64

In [ ]:
df1=df.groupby('Department').filter(lambda x : len(x)>2)
print(df1)

  Department Employee  Salary  Experience  Dept_Avg_Salary
1      Sales        B   60000           4     59666.666667
3      Sales        D   48000           5     59666.666667
6      Sales        G   71000           5     59666.666667

In [ ]:
#Mean salary by Department and Experience
df.pivot_table(
    values='Salary',
    index='Department',
    columns='Experience',
    aggfunc='mean'
)

Experience        2        3        4        5        6        7
Department
HR          50000.0      NaN      NaN      NaN      NaN  72000.0
IT              NaN  45000.0      NaN      NaN  70000.0      NaN
Sales           NaN      NaN  60000.0  59500.0      NaN      NaN

In [ ]:
df6=df.groupby('Department')['Employee'].count()
print(df6)

Department
HR       2
IT       2
Sales    3
Name: Employee, dtype: int64

In [ ]:
df7=df.groupby('Department')['Salary'].agg(['sum','mean','std'])
print(df7)

               sum          mean           std
Department
HR          122000  61000.000000  15556.349186
IT          115000  57500.000000  17677.669530
Sales       179000  59666.666667  11503.622618

In [ ]:
import pandas as pd
data={
    'Department':['ABM','Agronomy','GPB','Entomology','Pathology','Apiculture','Horticulture'],
    'Employee':['A','B','C','D','E','F','G'],
    'Salary':[40000,20000,30000,56000,80000,35000,100000],
    'Experience':[2,4,3,5,6,7,5]
}
df=pd.DataFrame(data)
print(df)

     Department Employee  Salary  Experience
0           ABM        A   40000           2
1      Agronomy        B   20000           4
2           GPB        C   30000           3
3    Entomology        D   56000           5
4     Pathology        E   80000           6
5    Apiculture        F   35000           7
6  Horticulture        G  100000           5

In [ ]:
df.groupby(['Department','Experience']).sum()
print(df)

     Department Employee  Salary  Experience
0           ABM        A   40000           2
1      Agronomy        B   20000           4
2           GPB        C   30000           3
3    Entomology        D   56000           5
4     Pathology        E   80000           6
5    Apiculture        F   35000           7
6  Horticulture        G  100000           5

In [ ]:
df7=df.groupby('Department')['Salary'].agg(['sum','mean','std'])
print(df7)

                 sum      mean  std
Department
ABM            40000   40000.0  NaN
Agronomy       20000   20000.0  NaN
Apiculture     35000   35000.0  NaN
Entomology     56000   56000.0  NaN
GPB            30000   30000.0  NaN
Horticulture  100000  100000.0  NaN
Pathology      80000   80000.0  NaN

In [ ]:
df6=df.groupby('Department')['Employee'].count()
print(df6)

Department
ABM             1
Agronomy        1
Apiculture      1
Entomology      1
GPB             1
Horticulture    1
Pathology       1
Name: Employee, dtype: int64

In [ ]:
#Mean salary by Department and Experience
df.pivot_table(
    values='Salary',
    index='Department',
    columns='Experience',
    aggfunc='mean'
)

Experience          2        3        4         5        6        7
Department
ABM           40000.0      NaN      NaN       NaN      NaN      NaN
Agronomy          NaN      NaN  20000.0       NaN      NaN      NaN
Apiculture        NaN      NaN      NaN       NaN      NaN  35000.0
Entomology        NaN      NaN      NaN   56000.0      NaN      NaN
GPB               NaN  30000.0      NaN       NaN      NaN      NaN
Horticulture      NaN      NaN      NaN  100000.0      NaN      NaN
Pathology         NaN      NaN      NaN       NaN  80000.0      NaN

In [ ]:
df.groupby('Department').agg({
    'Salary':'sum','Experience':'mean'
})
print(df)

     Department Employee  Salary  Experience
0           ABM        A   40000           2
1      Agronomy        B   20000           4
2           GPB        C   30000           3
3    Entomology        D   56000           5
4     Pathology        E   80000           6
5    Apiculture        F   35000           7
6  Horticulture        G  100000           5

In [ ]:
df1=df.groupby('Department').filter(lambda x : len(x)>2)
print(df1)

Empty DataFrame
Columns: [Department, Employee, Salary, Experience]
Index: []

In [ ]:
df9=df['Dept_Avg_Salary']=df.groupby('Department')['Salary'].transform('mean')
print(df9)

0     40000.0
1     20000.0
2     30000.0
3     56000.0
4     80000.0
5     35000.0
6    100000.0
Name: Salary, dtype: float64

In [ ]:
df5=df.groupby('Department')['Salary'].mean()
print(df5)

Department
ABM              40000.0
Agronomy         20000.0
Apiculture       35000.0
Entomology       56000.0
GPB              30000.0
Horticulture    100000.0
Pathology        80000.0
Name: Salary, dtype: float64

In [ ]:
df.groupby('Department')['Salary'].sum()

Department
ABM              40000
Agronomy         20000
Apiculture       35000
Entomology       56000
GPB              30000
Horticulture    100000
Pathology        80000
Name: Salary, dtype: int64

In [ ]:
df2=df.groupby('Department').sum()
print(df2)

             Employee  Salary  Experience  Dept_Avg_Salary
Department
ABM                 A   40000           2          40000.0
Agronomy            B   20000           4          20000.0
Apiculture          F   35000           7          35000.0
Entomology          D   56000           5          56000.0
GPB                 C   30000           3          30000.0
Horticulture        G  100000           5         100000.0
Pathology           E   80000           6          80000.0

In [ ]:
df2=df.groupby('Department').sum()
print(df2)

             Employee  Salary  Experience  Dept_Avg_Salary
Department
ABM                 A   40000           2          40000.0
Agronomy            B   20000           4          20000.0
Apiculture          F   35000           7          35000.0
Entomology          D   56000           5          56000.0
GPB                 C   30000           3          30000.0
Horticulture        G  100000           5         100000.0
Pathology           E   80000           6          80000.0

In [ ]:
df3=df.groupby('Salary').sum()
print(df3)

          Department Employee  Experience  Dept_Avg_Salary
Salary
20000       Agronomy        B           4          20000.0
30000            GPB        C           3          30000.0
35000     Apiculture        F           7          35000.0
40000            ABM        A           2          40000.0
56000     Entomology        D           5          56000.0
80000      Pathology        E           6          80000.0
100000  Horticulture        G           5         100000.0

In [ ]:
df99=df.groupby('Employee').sum()
print(df99)

            Department  Salary  Experience  Dept_Avg_Salary
Employee
A                  ABM   40000           2          40000.0
B             Agronomy   20000           4          20000.0
C                  GPB   30000           3          30000.0
D           Entomology   56000           5          56000.0
E            Pathology   80000           6          80000.0
F           Apiculture   35000           7          35000.0
G         Horticulture  100000           5         100000.0

In [ ]:
df0=df.groupby('Experience')['Employee'].sum()
print(df0)

Experience
2     A
3     C
4     B
5    DG
6     E
7     F
Name: Employee, dtype: object